function createfigure(X1, Y1, X2, Y2, X3, Y3)
%CREATEFIGURE(X1, Y1, X2, Y2, X3, Y3)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data

%  Auto-generated by MATLAB on 07-Feb-2017 19:07:25

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(2,2,3,'Parent',figure1);
hold(subplot1,'on');

% Create plot
plot(X1,Y1,'Parent',subplot1,'DisplayName','data1');

% Create xlabel
xlabel('runtime (s)');

% Create ylabel
ylabel('time to next TX (s)');

% Create title
title('diff(time to TX) + SF5');

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot1,[0 30]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot1,[-0.00201 0.1]);
box(subplot1,'on');
% Create subplot
subplot2 = subplot(2,2,2,'Parent',figure1);
hold(subplot2,'on');

% Create plot
plot(X2,Y2,'Parent',subplot2,'DisplayName','data2');

% Create xlabel
xlabel('runtime (s)');

% Create ylabel
ylabel('time to next TX (s)');

% Create title
title('diff(time to TX) + SF1');

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot2,[0 30]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot2,[-0.00201 0.1]);
box(subplot2,'on');
% Create subplot
subplot3 = subplot(2,2,1,'Parent',figure1);
hold(subplot3,'on');

% Create plot
plot(X3,Y3,'Parent',subplot3,'DisplayName','data3');

% Create xlabel
xlabel('runtime (s)');

% Create ylabel
ylabel('time to next TX (s)');

% Create title
title('diff(time to TX) + SF0');

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot3,[0 30]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot3,[-0.001 0.1]);
box(subplot3,'on');
% Create textbox
annotation(figure1,'textbox',...
    [0.302597402597403 0.859262007739986 0.162337665336228 0.0640465803240612],...
    'String',{'mean = 0.0012','std = 0.0021'});

% Create textbox
annotation(figure1,'textbox',...
    [0.705194805194805 0.859262007739987 0.200000003754726 0.0640465803240612],...
    'String',{'mean = 7.0390e-04','std = 0.0010'});

% Create textbox
annotation(figure1,'textbox',...
    [0.264935064935065 0.386190683140281 0.200000003754726 0.0640465803240612],...
    'String',{'mean = 8.6564e-04','std = 0.0015'});

